"use client";

import React, { useState } from "react";
import Image from "next/image";
// import clsx from 'clsx';

const tabs = [
  {
    label: "Solar Panels",
    image: "/images/overView/solarPanel.gif",
    content: (
      <>
        <p className="mb-4">
          In Victoria, Australia, under the Victorian Energy Upgrades (VEU)
          program, the electricity generated by solar panels is typically
          exported directly to the grid rather than being used by the household
          first. Here's how this system works and the benefits it provides:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>Solar Panel Installation:</strong> Solar panels are
            installed on your roof to capture sunlight and convert it into
            direct current (DC) electricity.
          </li>
          <li>
            <strong>Sunlight Absorption:</strong> During the day, the solar
            panels absorb sunlight, and the photovoltaic cells generate DC
            electricity.
          </li>
          <li>
            <strong>Inverter Conversion:</strong>The DC electricity is sent to
            an inverter, which converts it into alternating current (AC)
            electricity.
          </li>
          <li>
            <strong>Electricity Exported to the Grid:</strong> Instead of the
            electricity being used directly by your household, it is sent
            directly to the grid. The grid effectively acts as a "battery" for
            your solar energy.
          </li>
          <li>
            <strong>Household Draws Power from the Grid:</strong> Your household
            draws electricity from the grid as needed. You use the grid's
            electricity supply even if your solar system is generating
            electricity during the day.
          </li>
          <li>
            <strong>Feed-in Tariff:</strong> For the electricity you export to
            the grid, you receive a feed-in tariff. This credit is applied to
            your electricity bill, helping to offset the cost of the power you
            consume from the grid.
          </li>
        </ul>
      </>
    ),
  },
  {
    label: "Hot Water Heat Pump",
    image: "/images/overView/heatpumnp.gif",
    content: (
      <>
        <p className="mb-4">
          A hot water heat pump system in Australia works by using heat from the
          surrounding air to heat water. It is an energy-efficient way to heat
          water because it transfers heat instead of generating it directly.
          Here's how the system works step by step:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>Air Extraction:</strong> The heat pump system extracts heat
            from the surrounding air using a fan. Even at relatively low air
            temperatures, there is still some heat energy that the system can
            utilize.
          </li>
          <li>
            <strong>Heat Transfer:</strong> The extracted air is passed through
            an evaporator containing a refrigerant, which absorbs the heat from
            the air. This refrigerant changes from liquid to gas as it heats up.
          </li>
          <li>
            <strong>Compressor Operation:</strong> The gaseous refrigerant is
            compressed by the compressor, which significantly increases its
            temperature, making it suitable to transfer heat to the water.
          </li>
          <li>
            <strong>Heating Water:</strong> The hot refrigerant gas then flows
            through a heat exchanger where it transfers its heat to the water
            stored in the tank, thereby raising the water temperature.
          </li>
          <li>
            <strong>Refrigerant Cycle Repeats:</strong> The refrigerant then
            flows back to the evaporator to absorb more heat from the
            surrounding air, and the cycle repeats. This process continues until
            the water in the tank reaches the desired temperature.
          </li>
          <li>
            <strong>Water Storage and Use:</strong> The hot water is stored in
            an insulated tank, ready to be used for showers, washing, and other
            household purposes.
          </li>
          <li>
            <strong>Energy Efficiency:</strong> Because a heat pump system
            extracts heat from the air rather than generating it from
            electricity or gas, it is highly energy efficient. Typically, for
            every unit of electricity used, the system can produce three to four
            units of heat.
          </li>
        </ul>
      </>
    ),
  },
  {
    label: "Reverse Cycle Air Conditioner",
    image: "/images/overView/aircon.gif",

    content: (
      <>
      <p className="mb-4  text-gray-700 leading-relaxed">
  A reverse cycle air conditioning system, whether split or ducted, uses a heat pump to either absorb heat from outside and transfer it indoors during winter (heating mode) or absorb heat from inside and expel it outside during summer (cooling mode).
</p>

<h4 className="font-semibold text-base mb-2">Cooling Mode</h4>
<ol className="list-decimal pl-6 mb-4  text-gray-700 space-y-2 leading-relaxed">
  <li>
    <strong>Absorption of Heat:</strong> In cooling mode, the system absorbs heat from the indoor air and transfers it outside.
  </li>
  <li>
    <strong>Compressor Operation:</strong> The refrigerant circulates through the system, absorbing heat inside the house and releasing it outside via the external unit.
  </li>
  <li>
    <strong>Cool Air Circulation:</strong> The system then circulates cool air throughout the house, either through ducts (ducted system) or from the indoor unit (split system).
  </li>
</ol>

<h4 className="font-semibold text-base mb-2">Heating Mode</h4>
<ol className="list-decimal pl-6  text-gray-700 space-y-2 leading-relaxed">
  <li>
    <strong>Absorption of External Heat:</strong> In heating mode, the system reverses, absorbing heat from the outside air (even in cold conditions) and bringing it inside.
  </li>
  <li>
    <strong>Heat Pump Operation:</strong> The refrigerant carries the absorbed heat inside the house and releases it through the indoor unit or via the ducting system.
  </li>
  <li>
    <strong>Warm Air Circulation:</strong> The system circulates warm air throughout the house, keeping the indoor environment comfortable.
  </li>
</ol>

      </>
    ),
  },
];

const OverViewProduct = () => {
  const [selectedTab, setSelectedTab] = useState(0);

  return (
    <div className="px-5 md:px-12 xl:px-32  pb-8 md:py-12 xl:py-16">
      <h2 className="text-2xl lg:text-3xl font-bold text-center mb-8">
        An Overview of Products
      </h2>

      <div className="flex flex-wrap justify-center gap-4 mb-8">
        {tabs.map((tab, index) => (
          <button
            key={index}
            className={`px-6 py-2  rounded-md font-bold transition-all shadow-sm ${
              selectedTab === index
                ? "bg-[#59B445] text-white shadow-md"
                : "bg-white text-gray-700 hover:bg-gray-100 border border-gray-300"
            }`}
            onClick={() => setSelectedTab(index)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div className="grid lg:grid-cols-2 gap-8 items-center">
        <div>
          <Image
            src={tabs[selectedTab].image}
            alt={tabs[selectedTab].label}
            width={600}
            height={400}
            className="w-full h-auto  md:h-[400px] lg:h-[500px] rounded-xl shadow-md"
          />
        </div>
        <div className="text-gray-800 text-[16px] leading-relaxed">
          {tabs[selectedTab].content}
        </div>
      </div>
    </div>
  );
};

export default OverViewProduct;
