"use client";
import React, { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { GiSolarPower, GiBatteryPackAlt, GiWaterDrop } from "react-icons/gi";

import HeroSection from "./HeroSection";
import {
  FaMoneyBillWave,
  FaLeaf,
  FaBolt,
  FaGlobe,
  FaHome,
  FaSolarPanel,
} from "react-icons/fa";

import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay } from "swiper/modules";

import "swiper/css";
import Testimonials from "./Testimonails";
import ContactNewForm from "./ContactNewForm";

export default function SolarPanelInner() {
  const solarPanelPackages = [
    {
      title: "Solar Panels - Small",
      description: "For small to medium houses",
      inverter: "5 kW",
      system: "6.6 kW",
      image: "/images/solarPannel/1.webp",
      buttonText: "Get form",
    },
    {
      title: "Solar Panels - Medium",
      description: "For large houses",
      inverter: "8 kW",
      system: "10 kW",
      image: "/images/solarPannel/2.webp",
      buttonText: "Get form",
    },
    {
      title: "Solar Panels - Large",
      description: "For farm houses",
      inverter: "10-15 kW",
      system: "13-20 kW",
      image: "/images/solarPannel/3.webp",
      buttonText: "Get form",
    },
  ];

  const solarWork = {
    label: "Solar Panels",
    image: "/images/overView/solarPanel.gif",
    content: (
      <>
        <p className="mb-4">
          In Victoria, Australia, under the Victorian Energy Upgrades (VEU)
          program, the electricity generated by solar panels is typically
          exported directly to the grid rather than being used by the household
          first. Here's how this system works and the benefits it provides:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>
            <strong>Solar Panel Installation:</strong> Solar panels are
            installed on your roof to capture sunlight and convert it into
            direct current (DC) electricity.
          </li>
          <li>
            <strong>Sunlight Absorption:</strong> During the day, the solar
            panels absorb sunlight, and the photovoltaic cells generate DC
            electricity.
          </li>
          <li>
            <strong>Inverter Conversion:</strong>The DC electricity is sent to
            an inverter, which converts it into alternating current (AC)
            electricity.
          </li>
          <li>
            <strong>Electricity Exported to the Grid:</strong> Instead of the
            electricity being used directly by your household, it is sent
            directly to the grid. The grid effectively acts as a "battery" for
            your solar energy.
          </li>
          <li>
            <strong>Household Draws Power from the Grid:</strong> Your household
            draws electricity from the grid as needed. You use the grid's
            electricity supply even if your solar system is generating
            electricity during the day.
          </li>
          <li>
            <strong>Feed-in Tariff:</strong> For the electricity you export to
            the grid, you receive a feed-in tariff. This credit is applied to
            your electricity bill, helping to offset the cost of the power you
            consume from the grid.
          </li>
        </ul>
      </>
    ),
  };

  const slides = [
    {
      id: 1,
      img: "/images/posters/Solar System/Solar System Landscape (1200 x 628 px).webp",
    },
    {
      id: 2,
      img: "/images/posters/Solar System/Solar System Landscape (1200 x 628 px).webp",
    },
    {
      id: 3,
      img: "/images/posters/Solar System/Solar System Landscape (1200 x 628 px).webp",
    },
    {
      id: 4,
      img: "/images/posters/Solar System/Solar System Landscape (1200 x 628 px).webp",
    },
  ];

  const benefitsData = [
    {
      title: "Reduced Electricity Bills",
      description:
        "Feed-in tariffs help offset the cost of energy drawn from the grid.",
      icon: FaMoneyBillWave,
    },
    {
      title: "Support for Renewable Energy",
      description:
        "Contribute clean energy to the grid and reduce fossil fuel usage.",
      icon: FaLeaf,
    },
    {
      title: "VEU Program Incentives",
      description: "Take advantage of government rebates for energy upgrades.",
      icon: FaBolt,
    },
    {
      title: "Grid Stability",
      description:
        "Solar exports support grid supply and reduce blackout risks.",
      icon: FaGlobe,
    },
    {
      title: "Increased Property Value",
      description: "Homes with solar systems are more appealing to buyers.",
      icon: FaHome,
    },
    {
      title: "Environmental Impact",
      description:
        "Help reach net-zero emissions with renewable energy adoption.",
      icon: FaSolarPanel,
    },
  ];

  const benefits = [
    {
      img: "/images/posters/Solar System/Solar System Square Poster (1200 x 1200 px).webp",
      title: "Solar Panel System Benefits",
      description:
        "Save on bills, support clean energy, and boost property value with solar power in Victoria.",
      eligibility:
        "For eligible Victorian homes and businesses under solar rebate or VEU program.",
      installation: "Installed by certified providers with grid export setup.",
      energySavings: "Lower grid use and enjoy long-term energy savings.",
      features: [
        "Save on electricity with feed-in tariff credits.",
        "Support renewable energy and cut emissions.",
        "Get rebates via the VEU solar program.",
        "Help stabilize the grid during peak hours.",
        "Boost property value with sustainable features.",
        "Contribute to Victoria’s net-zero goal by 2050.",
      ],
    },
  ];

  return (
    <>
     
      <HeroSection slides={slides} />

    
     
      <section className="px-5 md:px-12 xl:px-32 py-8 md:py-12 xl:py-16 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl text-center md:text-4xl font-extrabold text-[#0F2C49] mb-12">
            Benefits of Going Solar in Victoria
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {benefitsData.map((item, index) => (
              <div
                key={index}
                className="bg-white shadow-md hover:shadow-lg transition-shadow duration-300 rounded-2xl p-6 flex gap-4 items-start border border-gray-100"
              >
                <div className="text-[#3F83C0] flex-shrink-0 mt-1">
                  {item.icon && React.createElement(item.icon, { size: 26 })}
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-gray-800 mb-2">
                    {item.title}
                  </h3>
                  <p className="text-sm text-gray-600">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-[#F9FAFB]   px-5 md:px-12 xl:px-32  py-8 md:py-12 xl:py-16 ">
        <div className="max-w-7xl mx-auto space-y-12">
          <div className="text-center space-y-6 mb-12">
            <h2 className="text-3xl text-center md:text-4xl font-extrabold text-[#0F2C49]">
              Residential and Commercial Solar Panel Solutions
            </h2>
          </div>

          <Swiper
            loop={true}
            autoplay={{
              delay: 4500,
              disableOnInteraction: false,
            }}
            modules={[Autoplay]}
            className="mySwiper lg:py-8"
          >
            {benefits.map((product, index) => (
              <SwiperSlide className="" key={index}>
                <div
                  className={`flex flex-col  ${
                    index % 2 == 0 ? "lg:flex-row" : "lg:flex-row-reverse"
                  } items-center justify-between bg-white p-4 md:p-8 rounded-xl shadow-xl hover:shadow-2xl transition-shadow transform hover:scale-105 duration-300`}
                >
                  <div className="w-full flex justify-center lg:w-1/2 mb-6 lg:mb-0">
                    <img
                      src={product.img}
                      alt={product.title}
                      className="w-auto h-auto  md:w-[90%] object-cover rounded shadow-md transform  transition-transform duration-300"
                    />
                  </div>

                  <div className="w-full lg:w-1/2 text-left space-y-6">
                    <h3 className="text-2xl font-semibold text-[#0F2C49] mb-3">
                      {product.title}
                    </h3>
                    <p className="text-base text-gray-700">
                      {product.description}
                    </p>

                    <div className="text-sm text-gray-700 space-y-2">
                      <p>
                        <strong>Eligibility:</strong> {product.eligibility}
                      </p>
                      <p>
                        <strong>Installation:</strong> {product.installation}
                      </p>
                      <p>
                        <strong>Energy Savings:</strong> {product.energySavings}
                      </p>
                    </div>

                    <div className="bg-green-100 text-green-700 p-4 rounded-md mb-6">
                      <h4 className="font-semibold text-xl mb-2">
                        Key Features:
                      </h4>
                      <ul className="list-disc pl-6 space-y-2">
                        {product.features.map((feature, featureIndex) => (
                          <li key={featureIndex} className="text-sm">
                            {feature}
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div className="flex gap-4">
                      <a
                        href="#form"
                        className="bg-yellow-400 group rounded px-6 sm:px-8 py-3 text-white font-semibold text-xs sm:text-sm relative overflow-hidden inline-flex items-center"
                      >
                        <span className="w-8 bg-yellow-500 group-hover:w-full group-hover:right-0 duration-300 transition-all skew-x-[-22deg] absolute inset-y-0 -right-4 opacity-40 group-hover:opacity-100 group-hover:skew-0"></span>
                        <span className="relative z-10">Enquiry</span>
                      </a>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </div>
      </section>


       <Testimonials />

      <div id="form">
        <ContactNewForm  service="Solar Panels"/>
      </div>
    </>
  );
}
